### ISSUE TITLE
Improve Stockfish performance on Android

### ISSUE THREAD

**Issue by gcp** [veloce/cordova-plugin-stockfish#10]
Some issues to try, I'll make pull requests if any work:

- Add -O3, by default Android only uses -O2 in release mode
- Add LOCAL_ARM_MODE := arm to Android.mk to avoid the code being built in Thumb mode
- Enable AArch64 builds

**Comment by veloce** [comment]
@gcp https://github.com/veloce/cordova-plugin-stockfish/commit/6ca005836a11237a68fab9ba9e373afafb177ff4

tested on my android, seems to work well.

**Comment by gcp** [comment]
NDK_TOOLCHAIN_VERSION := clang might also be worth a try.

**Comment by gcp** [comment]
Benchmarking on phones kinda sucks due to thermal throttling, but it seems -O3 is a clear win (~15%), LOCAL_ARM_MODE = arm may be a wash or even make things worse. Note that LOCAL_ARM_MODE won't affect 64-bit phones, so that needs to be tested on a 32-bit one.

Didn't test on my 64-bit device but I'm sure enabling Aarch64 is a massive win. 

Clang seems to be about 10% slower.

**Comment by veloce** [comment]
@gcp I haven't made a real benchmark, but with 7 threads and 1 pv, from the startup position, analysis was running at ~ 600 kn/s on my 64-bit device and previous app version. With that build, it is now running at ~ 1100 kn/s.
So yeah, I'd say a huge win :)  

Will remove LOCAL_ARM_MODE since I don't have a 32-bit phone to test for now.

**Comment by gcp** [comment]
Ok, I think we have all quick wins then. I tried building with LTO but that still seems to be too messy on Android, and doing it manually (by creating a single file that includes all others) didn't seem to work with the current Stockfish code.
